name: Test boolean inputs

on:
  workflow_dispatch:
    inputs:
      BOOLEAN_INPUT:
        description: input
        type: boolean
        default: true


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Echo if BOOLEAN_INPUT is true
          if: ${{ inputs.BOOLEAN_INPUT }}
          run: |
            echo "BOOLEAN_INPUT is true"
        - name: Echo if BOOLEAN_INPUT is false
          if: ${{ !inputs.BOOLEAN_INPUT }}
          run: |
            echo "BOOLEAN_INPUT is false"
        
        - name: Checkout repository
          uses: actions/checkout@v4
          with: 
            ref: jan-workflow-branch

        - name: ls
          run: ls ./.github/workflows/

        - name: Call
          uses: ./.github/workflows/echo.yml
