name: Build And Publish Artifacts
on:
  workflow_dispatch:
    inputs:
      PULL_REQUEST_NUMBER:
        description: Pull Request number, if not specified defaults to main branch.
        required: true
        type: number

jobs:
  build-react-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout on PR branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=${{ github.event.inputs.PULL_REQUEST_NUMBER }}
          gh pr checkout ${PR_NUMBER}

      - name: Modify customBuildsMap.json
        run: |
          JSON_FILE="customBuildsMap.json"
          
          if [ -f "$JSON_FILE" ]; then
            echo "$JSON_FILE found. Updating the file."
            jq '. + {"ABC": "123"}' "$JSON_FILE" > temp.json && mv temp.json "$JSON_FILE"
          else
            echo "$JSON_FILE not found. Creating the file."
            echo '{"ABC": "123"}' > "$JSON_FILE"
          fi

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add customBuildsMap.json
          git commit -m "Add new entry to customBuildsMap.json"
          git push

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Clone React Native repository and checkout to correct branch
        run: |
          git clone --branch v0.78.0 --depth 1 https://github.com/facebook/react-native.git ${{ github.workspace }}/react-native

      - name: Copy patched react-native to cloned repository
        run: |
          cp -rT node_modules/react-native ${{ github.workspace }}/react-native/packages/react-native

      - name: Build artifacts
        run: |
          cd ${{ github.workspace }}/react-native
          yarn
          yarn --cwd packages/react-native-codegen build
          
          export ANDROID_NDK_VERSION="$(basename "$ANDROID_NDK")"
          
          ./gradlew assembleRelease
