name: Build And Publish Artifacts
on:
  workflow_dispatch:
    inputs:
      PULL_REQUEST_NUMBER:
        description: Pull Request number, if not specified defaults to main branch.
        required: true
        type: number

jobs:
  update-custom-builds:
    runs-on: ubuntu-latest
    outputs:
      react_native_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout on PR branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=${{ github.event.inputs.PULL_REQUEST_NUMBER }}
          gh pr checkout ${PR_NUMBER}

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Make script executable
        run: |
          chmod +x .github/scripts/computePatchesHash.sh

      - name: Modify customBuildsMap.json
        run: |
          JSON_FILE="customBuildsMap.json"
          HASH=$(.github/scripts/computePatchesHash.sh)
          
          LATEST_VALUE=$(jq -r '.latest' "$JSON_FILE")
          PREFIX=$(echo "$LATEST_VALUE" | sed -E 's/^(.*)-[0-9]+$/\1/')
          NUMBER=$(echo "$LATEST_VALUE" | sed -E 's/^.*-([0-9]+)$/\1/')

          NEW_NUMBER=$((NUMBER + 1))
          NEW_LATEST_VALUE="$PREFIX-$NEW_NUMBER"

          jq --arg newLatest "$NEW_LATEST_VALUE" '.latest = $newLatest' "$JSON_FILE" > temp.json && mv temp.json "$JSON_FILE"          
          jq --arg hash "$HASH" --arg value "$NEW_LATEST_VALUE" '. + {($hash): $value}' "$JSON_FILE" > temp.json && mv temp.json "$JSON_FILE"
          
          cat $JSON_FILE

      - name: Get react-native version
        id: get_version
        run: |
          VERSION=$(jq -r '.dependencies["react-native"]' package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload react-native module
        uses: actions/upload-artifact@v4
        with:
          name: react-native-module
          path: node_modules/react-native/

  publish-react-native:
    needs: update-custom-builds
    runs-on: ubuntu-latest 
    container:
      image: reactnativecommunity/react-native-android:latest
      env:
        TERM: "dumb"
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    steps:
      - name: Download react-native module
        uses: actions/download-artifact@v4
        with:
          name: react-native-module
          path: node_modules/react-native/

      - name: Setup temporary react-native repository
        run: |
          TEMP_REACT_NATIVE_DIR=$(mktemp -d ./tmp-react-native-repoXXX)
          VERSION="${{ needs.update-custom-builds.outputs.react_native_version }}"
          git clone --branch "v${VERSION}" --single-branch --depth 1 https://github.com/facebook/react-native.git $TEMP_REACT_NATIVE_DIR
          cp -r ./node_modules/react-native/ReactAndroid $TEMP_REACT_NATIVE_DIR/packages/react-native/
          echo "TEMP_REACT_NATIVE_DIR=$TEMP_REACT_NATIVE_DIR" >> $GITHUB_ENV

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          build-root-directory: ${{ env.TEMP_REACT_NATIVE_DIR }}

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create react-native artifacts
        run: |
          cd ${{ env.TEMP_REACT_NATIVE_DIR }} 
          yarn install --non-interactive
          ./gradlew build