name: Compute Hash of Patches

on:
  pull_request:

jobs:
  compute-hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: |
          ls -a
          chmod +x .github/scripts/computePatchesHash.sh

      - name: Compute hash
        run: |
          HASH=$(.github/scripts/computePatchesHash.sh)
          echo "Hash: $HASH" | tee -a $GITHUB_STEP_SUMMARY
