name: Compute Hash of Patches

on:
  pull_request:

jobs:
  compute-hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: |
          chmod +x .github/scripts/computePatchesHash.sh

      - name: Compute hash and check if version exists
        run: |
          HASH=$(.github/scripts/computePatchesHash.sh)
          echo "Hash: $HASH" | tee -a $GITHUB_STEP_SUMMARY
          
          if [ -f "customBuildsMap.json" ]; then
            ENTRY=$(jq -r --arg hash "$HASH" '.[$hash] // empty' customBuildsMap.json)
            if [ -n "$ENTRY" ]; then
              echo "Matching entry found: $ENTRY" | tee -a $GITHUB_STEP_SUMMARY
            fi
          fi
